export { default as StatsDialog } from './StatsDialog/StatsDialog.component'
export { default as HowToPlayDialog } from './HowToPlayDialog/HowToPlayDialog.component'
export { default as HowToCalculateStatsDialog } from './HowToCalculateStatsDialog/HowToCalculateStatsDialog.component'
export { default as CreditsDialog } from './CreditsDialog/CreditsDialog.component'
export { default as ContactDialog } from './ContactDialog/ContactDialog.component'
export { default as MenuDialog } from './MenuDialog/MenuDialog.component'
export { default as InterstitialAdDialog } from './InterstitialAdDialog/InterstitialAdDialog.component'
